# -*- coding: utf-8 -*-
"""Agentic Rag_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17T1vkJswNfcp-QiAXMj4abgN5DYT5aAv
"""

!pip install chromadb langchain-community langchain-text-splitters langchain-huggingface

import os
import json
import requests
import gradio as gr
import chromadb
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings

import requests
OPENROUTER_API_KEY = "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"

LLM_MODEL = "nvidia/nemotron-3-nano-30b-a3b:free"

def call_llm(prompt, system_prompt="You are a helpful AI assistant."):
    """Helper function to call the OpenRouter API."""
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }
    data = {
        "model": LLM_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ]
    }
    response = requests.post(
        url="https://openrouter.ai/api/v1/chat/completions",
        headers=headers,
        json=data
    )
    if response.status_code == 200:
        return response.json()['choices'][0]['message']['content']
    else:
        return f"Error from LLM API: {response.text}"

"""Cell 3: Knowledge Base & Document Ingestion"""

global_full_text = ""
chroma_client = chromadb.Client()
collection_name = "assignment_collection"

try:
    chroma_client.delete_collection(name=collection_name)
except:
    pass
collection = chroma_client.create_collection(name=collection_name)

embeddings_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

def ingest_pdf(file_path):
    global global_full_text

    print(f"Loading {file_path}...")
    loader = PyPDFLoader(file_path)
    documents = loader.load()

    # Save full text for the summarize tool
    global_full_text = "\n".join([doc.page_content for doc in documents])

    print("Chunking document...")
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100)
    chunks = text_splitter.split_documents(documents)

    texts = [chunk.page_content for chunk in chunks]

    metadatas = [{"page": str(chunk.metadata.get('page', 'Unknown'))} for chunk in chunks]
    ids = [f"chunk_{i}" for i in range(len(chunks))]

    print("Creating embeddings and storing in ChromaDB...")
    embedded_texts = embeddings_model.embed_documents(texts)
    collection.add(
        embeddings=embedded_texts,
        documents=texts,
        metadatas=metadatas,
        ids=ids
    )
    print(f"Success! Processed {len(documents)} pages into {len(chunks)} searchable chunks.")

def summarize_tool(query_ignored):
    print(">> Executing Summarize Tool...")
    truncated_text = global_full_text[:15000]
    prompt = f"Provide a comprehensive, well-structured executive summary of the following document:\n\n{truncated_text}"
    system = "You are an expert summarizer. Abstract the main points clearly."
    return call_llm(prompt, system)

def qa_tool(query):
    print(">> Executing General Q&A Tool...")
    query_embedding = embeddings_model.embed_query(query)
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=4
    )

    context = ""
    citations = []

    for i in range(len(results['documents'][0])):
        doc_text = results['documents'][0][i]
        page_num = int(results['metadatas'][0][i]['page']) + 1
        context += f"--- Chunk {i+1} (Page {page_num}) ---\n{doc_text}\n\n"
        citations.append(f"Page {page_num}")

    unique_citations = list(set(citations))

    prompt = f"Answer the user's question based ONLY on the provided context.\n\nContext:\n{context}\n\nQuestion: {query}"
    system = "You are a precise Q&A assistant. If the answer is not in the context, say so."

    answer = call_llm(prompt, system)

    return f"{answer}\n\n**Sources Consulted:** {', '.join(unique_citations)}"

def hindi_translation_tool(query):
    print(">> Executing Hindi Explanation Tool...")
    query_embedding = embeddings_model.embed_query(query)
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=3
    )

    context = "\n".join(results['documents'][0])
    prompt = f"Read the following context and answer the user's question. Your final response MUST be entirely in Hindi.\n\nContext:\n{context}\n\nQuestion: {query}"
    system = "You are a bilingual expert. You read English context but explain and answer strictly in Hindi."

    return call_llm(prompt, system)

def agent_dispatcher(query):
    if not global_full_text:
        return "System Error", "Please ingest a PDF document first."

    prompt = f"""Analyze the following user query and classify their intent.
    Return ONLY ONE of the following exact words:
    - SUMMARIZE : If they ask for an overview, summary, or abstract of the whole document.
    - HINDI : If they explicitly ask for an explanation or translation in Hindi.
    - QA : If they are asking a specific question or looking for details in the document.

    Query: "{query}"
    """

    intent_response = call_llm(prompt, system_prompt="You are a strict routing agent. Output only one word.").strip().upper()

    if "SUMMARIZE" in intent_response:
        active_tool = "Summarize Tool"
        response = summarize_tool(query)
    elif "HINDI" in intent_response:
        active_tool = "Hindi Explanation Tool"
        response = hindi_translation_tool(query)
    else:
        active_tool = "General Q&A Tool"
        response = qa_tool(query)

    return active_tool, response

!pip install PyPDF

pdf_path = "/content/LLM.pdf"

# Ingest the document
ingest_pdf(pdf_path)

print("\n" + "="*50)

user_query = "Give the summary of this pdf"

# 3. Run the dispatcher
tool_used, final_answer = agent_dispatcher(user_query)

print(f"USER QUERY: {user_query}")
print(f"ROUTED TO TOOL: [{tool_used}]")
print("="*50 + "\n")
print(final_answer)

pdf_path = "/content/LLM.pdf"

ingest_pdf(pdf_path)

print("\n" + "="*50)


user_query = "What is LLM and What are pretrained models?"


# 3. Run the dispatcher
tool_used, final_answer = agent_dispatcher(user_query)

print(f"USER QUERY: {user_query}")
print(f"ROUTED TO TOOL: [{tool_used}]")
print("="*50 + "\n")
print(final_answer)

pdf_path = "/content/LLM.pdf"

# Ingest the document
ingest_pdf(pdf_path)

print("\n" + "="*50)

user_query = "can you explain me about BERT"

tool_used, final_answer = agent_dispatcher(user_query)

print(f"USER QUERY: {user_query}")
print(f"ROUTED TO TOOL: [{tool_used}]")
print("="*50 + "\n")
print(final_answer)